language: python
os:
  - "linux"
#  - "osx"
python:
  - "2.7"
  - "3.4"
  - "3.5"
#  - "3.6"
# command to install dependencies
install: 
  - "pip install -r requirements.txt"
# command to run tests
script: 
  - "./save_all.sh"
  - "./test.it"
after_success:
  - "codecov -t 7f3da6c1-f9f9-449a-a145-b09f060336ed"
